name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Compile TypeScript
        run: pnpm run build
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Lint
        run: pnpm run lint
  style:
    name: Check style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Check style
        run: pnpm run style
  test:
    name: Run unit tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Run tests
        run: pnpm run test
      - name: Submit test coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: Publish

    runs-on: ubuntu-latest

    if: ${{ github.ref  == 'refs/heads/main' }}

    needs: [build, lint, style, test]

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Publish release
        run: pnpm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
